version: "3.5"
services:

  # Following webserver was provided by MoodleHQ.
  #
  # webserver:
  #   image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
  #   depends_on:
  #     - db
  #   volumes:
  #     - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
  #     - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
  #   environment:
  #     MOODLE_DOCKER_DBTYPE: pgsql
  #     MOODLE_DOCKER_DBNAME: moodle
  #     MOODLE_DOCKER_DBUSER: moodle
  #     MOODLE_DOCKER_DBPASS: "m@0dl3ing"
  #     MOODLE_DOCKER_BROWSER: firefox
  #     MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"

  webserver:
    build: 
        context: ./dockerfiles
        dockerfile: nginx.docker
        args:
          CONTAINER_USER_ID: "$DOCKER_UID"
          CONTAINER_GROUP_ID: "$DOCKER_GID"
    image: monash/moodle-webserver:latest
    volumes:
        - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
        - "${MOODLE_DOCKER_MOODLEDATAROOT}:/var/www/moodledata"
        - "${MOODLE_DOCKER_PHPUNITDATAROOT}:/var/www/phpunitdata"
        - "${MOODLE_DOCKER_BEHATDATAROOT}:/var/www/behatdata"
        - "${MOODLE_DOCKER_BEHATFAILDUMPSDATAROOT}:/var/www/behatfaildumps"
        - "${MOODLE_DOCKER_WEBSERVERLOGS}/access.log:/var/log/nginx/access.log"
        - "${MOODLE_DOCKER_WEBSERVERLOGS}/error.log:/var/log/nginx/error.log"
        - "./nginx/moodle.conf:/etc/nginx/conf.d/default.conf"
        - "./nginx/mailhog.conf:/etc/nginx/conf.d/mailhog.conf"
        - "./nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf"
    depends_on:
        - db
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_WEB_HOST: webserver.localdomain
    networks:
        moodle:
          aliases:
            - mailhog
            - jenkins

  phpfpm:
    build: 
        context: ./dockerfiles
        dockerfile: phpfpm.docker
        args:
          CONTAINER_USER_ID: "$DOCKER_UID"
          CONTAINER_GROUP_ID: "$DOCKER_GID"
          MOODLE_DOCKER_PHP_VERSION: 7.2
    image: monash/moodle-phpfpm:latest
    ports:
      - "9000:9000"
    volumes:
        - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
        - "${MOODLE_DOCKER_MOODLEDATAROOT}:/var/www/moodledata"
        - "${MOODLE_DOCKER_PHPUNITDATAROOT}:/var/www/phpunitdata"
        - "${MOODLE_DOCKER_BEHATDATAROOT}:/var/www/behatdata"
        - "${MOODLE_DOCKER_BEHATFAILDUMPSDATAROOT}:/var/www/behatfaildumps"
        - "./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_WEB_HOST: webserver.localdomain
      CONTAINER_USER_ID: "$DOCKER_UID"
      CONTAINER_GROUP_ID: "$DOCKER_GID"
    networks:
        - moodle

  db:
    build: 
        context: ./dockerfiles
        dockerfile: postgres.docker
        args:
          CONTAINER_USER_ID: "$DOCKER_UID"
          CONTAINER_GROUP_ID: "$DOCKER_GID"
          MOODLE_DOCKER_POSTGRES_VERSION: 9.4
    image: monash/moodle-postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: moodle
    volumes:
     - "${MOODLE_DOCKER_POSTGRESDATAROOT}:/var/lib/postgresql/data"
    networks:
        - moodle
  
  exttests:
    image: moodlehq/moodle-exttests
  
  selenium:
    image: "selenium/standalone-firefox${MOODLE_DOCKER_SELENIUM_SUFFIX}:2.53.1"
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html:ro"
    networks:
        - moodle

  mailhog:
    image: mailhog/mailhog
    networks:
        - moodle

  # If local jenkins needed.
  # jenkins:
  #   build: 
  #     context: ./dockerfiles
  #     dockerfile: jenkins.docker
  #     args:
  #       CONTAINER_USER_ID: "$DOCKER_UID"
  #       CONTAINER_GROUP_ID: "$DOCKER_GID"
  #   image: monash/moodle-jenkins:latest
  #   ports:
  #     - '8080:8080'
  #   environment:
  #     - host_dir=/path/to/jenkins/data
  #   volumes:
  #     - "${MOODLE_DOCKER_JENKINSDATAROOT}:/var/jenkins_home"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   networks:
  #     - moodle
        
networks:
  moodle:
    name: localdomain
